//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condi.DBStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int EquipmentTypeId { get; set; }
        public string DeviceModel { get; set; }
        public string ProblemDescription { get; set; }
        public string ClientName { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ExecutorId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Status Status { get; set; }
    }
}
